#!/usr/bin/env python3
"""Write a reviewable coverage map from a successful local verification run."""
import csv
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
report = json.loads((root / '.build/verification.json').read_text())
if not report['native_verified'] or report.get('generator_tests') != 'passed':
    raise SystemExit('Full native verification is required before recording coverage')
with (root / '.build/fixture-manifest.csv').open() as f:
    calls = list(csv.DictReader(f))
inventory_path = root / 'tests/parity/r-test-inventory.json'
inventory = json.loads(inventory_path.read_text())
rows = []
generator_cases = 0
for test in inventory['tests']:
    filename = Path(test['r_file']).name
    matches = [c for c in calls if c['file'] == filename and c['test'] == test['test']]
    exported = [c['id'] for c in matches if c['status'] == 'exported']
    generator = filename.startswith('test-rgen') or test['test'] == 'dgp.po warning work'
    test['r_baseline'] = 'passed'
    test['captured_call_ids'] = [int(c['id']) for c in matches]
    if exported:
        test['status'] = 'estimator-calls-verified'
        test['stata_tests'] = ['.build/parity.do (generated)', 'tests/stata/test-native.do']
        coverage = f'{len(exported)} estimator calls replayed'
    elif filename in ('test-cluster-large-variance.R', 'test-cluster-small-correction.R', 'test-design-classifier-warning.R'):
        test['status'] = 'internal-helper-verified'
        test['stata_tests'] = ['.build/internal.do (generated by tools/export-internal-fixtures.R)']
        coverage = 'Direct internal-helper translation'
    else:
        test['status'] = 'r-baseline-only'
        test['stata_tests'] = []
        coverage = 'R baseline only'
    if generator:
        generator_cases += 1
        test['native_generator'] = 'design-and-distribution-verified'
        test['stata_tests'].append('tests/stata/test-generator.do')
        if not exported:
            test['status'] = 'native-generator-verified'
            coverage = 'Native generator design/validation translation'
        else:
            coverage += '; native generator design/validation translation'
    rows.append(f'| `{filename}` | {test["test"].replace("|", "/")} | {coverage} |')
inventory_path.write_text(json.dumps(inventory, indent=2) + '\n')
text = '''# R-to-Stata coverage

Every original R test is retained unchanged and passes in the reference run.
The table distinguishes replayed estimator calls, direct native helper tests,
and native generator design/distribution translations. It does not
claim a literal Stata translation of every R assertion or output string.

The generated parity suite verifies numerical inference, warnings and output
metadata. Native tests cover parser/container equivalents, replay, factor
variables, sample selection, postestimation and plots. Plot aesthetics use
Stata conventions rather than reproducing ggplot objects or viridis gradients.

| R test file | Test | Native coverage |
| --- | --- | --- |
''' + '\n'.join(rows) + '\n'
(root / 'tests/parity/coverage.md').write_text(text)
dest = root / 'tests/results'
dest.mkdir(exist_ok=True)
(dest / 'verification.json').write_text(json.dumps(report, indent=2) + '\n')
(dest / 'latest.md').write_text(f'''# Verification report

Run timestamp (UTC): {report['timestamp_utc']}

R reference: `{report['r_commit']}` (sreg 2.1.0).

Verified using R {report['r_version']} and licensed Stata {report['stata_version']}.
Platform: {report['platform']}.

- Original R suite: **{report['r_tests']} test cases, {report['r_assertions']} assertions passed**.
- R documentation examples: executed and included in captured estimator calls.
- Native replay suite: **{report['native_cases']} passed** ({report['numerical_cases']} numerical cases,
  {report['error_cases']} expected errors).
- R container/type-specific calls: {report['r_container_cases']}; corresponding native parser checks passed.
- Internal helper translations: passed, including the multi-arm cluster
  variance correction, small-cluster estimators and classifier rules.
- Native interface, stored results, replay, factor variables, sample marking,
  cluster row-order invariance and inferred sizes: passed.
- `lincom`, joint tests and analytic full-covariance examples: passed.
- Native graph creation and preservation of data/results: passed.
- Native generator design, allocation, effects, reproducibility, validation,
  covariate output and distribution checks: passed.
- Local `net install` into an isolated ado directory and runnable examples: passed.

Numerical tolerance: `{report['tolerance']}`. Analytic and equivalence checks
use tighter tolerances. Raw build artifacts are regenerated with
`python3 tools/test.py`; no licensed Stata binary or license metadata is shipped.

## Remaining scope

Native generator tests now cover the intentions of the {generator_cases} generator-related
R cases. R and Stata use different random streams; no identical-seed parity
is claimed. See [generator adaptations](../../docs/generator.md) for intentional
edge-case fixes and [the coverage map](../parity/coverage.md) for the mapping.
The plotting command uses native Stata styles instead of reproducing every
R styling argument. This local report does not claim that hosted CI ran
licensed Stata or that every R-specific object assertion has a literal port.
''')
print(f'Updated coverage for {len(rows)} R tests; {generator_cases} include verified native generator scope.')
